language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-malozanom
  api_key:
    secure: SapSVGFQbuwJrwoYew7OEUTTGU9+xy+HPBJUPR5EKST1ea3ua5wy/n3CwDEtNy0wI6IvInX4Hg8wKkq7o8cs/ZrFIGJi2rn9O77IKga5QuHuxmnRIqn1bEHrrAp6Q8lgOzx/i9E7Wysgvai3/wRRY3HNsCoL5VK1Xp98j3ICmCMCwYqpg9LJgN1QaWHaXW9ScA9N3OfhC/QEJWXT6HQWkR6iUK8BrJRk4OssV4qYgCyT+z9yWi5kHqX2XN6E83VrNx5c+UUWJnq/CJYSCKuhfKaEsu+UHFS+z7KDP59xPpMufkLwcdUSKzwnHYrQk8dAoBlFNh6X6Ord7RrBB7/dWn0WvV0MoF4/03YioyMw01WAwNJKWXJS1ft7W6l7dlAZOUnPMdsIhqbm4PnSli/SGNs/mlNWfIV90gg5aMua0v36+L0gg2g1FjPZrgXE5y1nrXQnXPy0ZMMZCrbuBNxxnqK/97M17jx9kkCPiNCP5jCkOB01NZpVP5azg/bq6+puuLFHdohR+KiJfVGiSI6ksjcjtP68rGFsEq7izaHHpUXINHZ4WVwE1/+s7lGnk+jaN9ja1n+wRoovBMa32QQBOF1zhwlCHEMtULr1xXWgCoHFD1jpI1WQK5rmj1ALNJ0I6snMDSziHd8C+q2R1krBKc6o4xfQfYnl77kW+jlb6fA=
